dataset:
  dataset: mnist
  image_split: true
  show_dataset: true
  validation_split: 0.85
evaluation:
  evaluation_snr: 20
  mode: 0
  snr_range:
  - -30
  - 20
  snr_step_size: 1
  validation_rounds: 10
load_settings:
  filename: ResNet14_MNIST4_RL_adam_Ne6000_snr-4_6_conv8
  gpu: -2
  load: true
  numerical_precision: float32
  path: models/mnist_rl
  save_format: npz
  simulation_filename_prefix: ''
  simulation_filename_suffix: _results
  use_weights_format: true
model:
  communication:
    image_split_factor: 2
    number_channel_uses: 14
    number_txrx_layer: 1
    power_normalization_axis: 0
    rx_layer_width: 56
    rx_linear: false
    rx_same: 1
    transceiver_split: 1
    weight_decay: 0
    weight_initialization: he_uniform
  noise:
    active: true
    snr_max_train: 6
    snr_min_train: -4
  resnet:
    architecture: cifar10
    batch_normalization: true
    bottleneck: false
    multi_image_layer_number: 0
    multi_image_layer_width: 0
    number_filters: 14
    number_residual_units: 2
    number_resnet_blocks: 3
    preactivation: true
    weight_decay: 0.0001
    weight_initialization: he_uniform
reinforcement_learning:
  active: 1
  exploration_boundaries:
  - []
  exploration_variance:
  - 0.15
  iteration_print: 10
  number_epochs_receiver_finetuning: 600
  own_optimizer_rxfinetuning: false
  rx_steps: 10
  tx_steps: 10
training:
  batch_size: 500
  learning_rate: 0.001
  learning_rate_schedule:
    active: false
    epoch_bound:
    - 3
    - 6
    values:
    - 0.1
    - 0.01
    - 0.001
  momentum: 0.9
  number_epochs: 6000
  optimizer: adam
  validation_dataset_size: 1000
